name: Lint Code Base

on:
  push:
  pull_request:
    branches:
      - main # Adjust this branch name as needed

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2 # Use v2 for the checkout action

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: "false" 

